AssignmentManagement/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views
from assignment import views


urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('assignment/', include('assignment.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/assignment/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib.auth import views as auth_views
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment/urls.py
from django.urls import path
from . import views

#faculty dashboard
urlpatterns = [
    #path('',views.index,name='home')
    path('filter/',views.filter,name="FilterQuestions"),
    path('FacultyRegistration/',views.FacultyRegistration,name='FacultyRegistration'),
    path('StudentRegistration/',views.StudentRegistration,name='StudentRegistration'),
    path('',views.QuestionListView.as_view(),name='index'),
    path('FacultyDashboard',views.FacultyDashboard,name='FacultyDashboard'),
    path('question/<int:pk>', views.RepoQuestionDetailView.as_view(), name='repo-question-detail'),
    path('addCourse/', views.CourseCreate.as_view(), name='CreateCourse'),
    path('course/<int:pk>/update/', views.CourseUpdate.as_view(), name='UpdateCourse'),
    path('course/<int:pk>/delete/', views.CourseDelete.as_view(), name='DeleteCourse'),
    path('course/<int:pk>', views.CourseDetailView.as_view(), name='course_detail'),
    path('course_list/',views.CourseListView.as_view(),name='ViewCourse'),
    path('addAssignment/', views.AssignmentCreate.as_view(), name='CreateAssignment'),
    path('assignment_list/',views.AssignmentListView.as_view(),name='ViewAssignment'),
    path('assignment/<int:pk>/update/', views.AssigmentUpdate.as_view(), name='UpdateAssignment'),
    path('Courseassignment/<int:pk>/update/', views.CourseAssigmentUpdate.as_view(), name='UpdateCourseAssignment'),
    path('assignment/<int:pk>/delete/', views.AssignmentDelete.as_view(), name='DeleteAssignment'),
    path('Courseassignment/<int:pk>/delete/', views.CourseAssignmentDelete.as_view(), name='DeleteCourseAssignment'),
    path('assignment/<int:pk>/', views.AssignmentDetailView.as_view(), name='assignment_detail'),
    path('<int:pk>/createQuestion/', views.QuestionCreate, name='CreateQuestion'),
    path('<int:assignment_pk>/UpdateQuestion/<int:question_pk>', views.QuestionUpdate, name='UpdateQuestion'),
    path('<int:assignment_pk>/DeleteQuestion/<int:pk>/delete', views.QuestionDeleteView.as_view(), name='DeleteQuestion'),
    path('submittedAnswers/<int:id>', views.getSubmittedAnswer, name='AllSubmittedAnswers'),
    path('rejectAnswer/<int:qid>/<int:ansID>', views.rejectAnswer, name='RejectAnswer'),
    path('addQuestionBank/',views.questionBank,name='QuestionBank'),
    # path('addQuestionBank/brand/<int:pk>/all_json_models/',views.all_json_models),\
    path('addQuestionBank/selectedCourse/<int:id>/all_json_assignments',views.all_json_models, name="SendCourse"),
    path('addQuestionBank/getQuestions/',views.generateQB, name='GetQuestions'),
    path('generateModelAnswer/<int:id>', views.generateModelAnswer, name='generateModelAnswer'),
    path('modelAnswer/<int:id>', views.modelAnswer, name='viewModelAnswer')
]


#STudent dashboard
urlpatterns += [
    path('StudentDashboard',views.StudentDashboard,name='StudentDashboard'),
    path('student_course_list/',views.StudentCourseListView.as_view(),name='AllCourse'),
    path('student_assigment_list/',views.StudentAssignmentListView.as_view(),name='AllAssignment'),
    path('student_course/<int:pk>', views.StudentCourseDetailView.as_view(), name='student_course_detail'),
    path('student_assignment/<int:pk>/', views.StudentAssignmentDetailView.as_view(), name='student_assignment_detail'),
    # path('<int:pk>/<int:qpk>/addAnswer/',views.StudentAddAnswer.as_view(),name ='StudentAddAnswer'),
    # path('<int:pk>/<int:qpk>/UpdateAnswer/<int:ak>',views.StudentUpdateAnswer.as_view(),name ='StudentUpdateAnswer'),
    path('<int:pk>/createAnswer/', views.AnswerCreate, name='CreateAnswer'),
    path('<int:apk>/student_answer/<int:pk>/', views.getAnswer ,name='student_answer'),
    # path('student_answer/<int:pk>/', views.StudentAnswerDetailView.as_view(), name='student_answer_detail'),
    # path('student_question/<int:pk>/', views.StudentQuestionDetailView.as_view(), name='student_question_detail'),
]

assignment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
#if hasattr(self, 'student'):


class StudyYear(models.Model):
    year = models.CharField(max_length = 50 , help_text = "Enter in this format First Year , Second Year, etc.")

    def __str__(self):
        return self.year

class Semester(models.Model):
    sem = models.IntegerField()

    def __str__(self):
        return f'semester {self.sem}'


class Branch(models.Model):
    name = models.CharField(max_length = 50 , help_text = "Example Computer Engineering")

    def __str__(self):
        return self.name

class Faculty(models.Model):
    user = models.OneToOneField(User, on_delete =models.CASCADE)
    branch = models.ForeignKey(Branch , on_delete = models.SET_NULL,null=True)
    code = models.CharField(max_length=30 ,blank = True, unique = True)
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

class Student(models.Model):
    user = models.OneToOneField(User , on_delete =models.CASCADE)
    rollnumber = models.CharField(max_length = 10)
    branch = models.ForeignKey(Branch , on_delete = models.SET_NULL , null=True)
    year = models.ForeignKey(StudyYear , on_delete = models.SET_NULL , null=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

class Course(models.Model):
    name = models.CharField(max_length = 50)
    branch = models.ForeignKey(Branch,on_delete = models.SET_NULL,blank=True,null=True)
    faculty = models.ForeignKey(Faculty ,on_delete = models.SET_NULL,blank=True,null=True)
    year = models.ForeignKey(StudyYear ,on_delete = models.SET_NULL,blank=True,null=True)
    semester = models.ForeignKey(Semester ,on_delete = models.SET_NULL,blank=True,null=True )

    def __str__(self):
        return self.name
    # def get_absolute_url(self):
    #     """Returns the url to access a detail record for this book."""
    #     return reverse('course-detail', args=[str(self.id)])

class Assignment(models.Model):
    number = models.IntegerField()
    course = models.ForeignKey(Course,on_delete = models.SET_NULL,blank=True,null=True)
    publish_date = models.DateField(auto_now_add = True)
    deadline_date = models.DateField()
    faculty = models.ForeignKey(Faculty,on_delete = models.SET_NULL,blank=True,null=True)

    def __str__(self):
        return f'Assignment {self.number}-{self.course}'

    def get_absolute_url(self):
        """Returns the url to access a detail record for this Assignment."""
        return reverse('assignment-detail', args=[str(self.id)])

class Question(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.SET_NULL,blank=True,null=True)
    username = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)
    title = models.CharField(max_length = 200)
    description = models.TextField(blank=True , null = True)
    modelAnswer = models.TextField(blank=True)
    marks = models.IntegerField(null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('repo-question-detail', args=[str(self.id)])

    def getPublishedAnswerCount(self):
        return self.answer_set.filter(status = 'Published').count()

class Answer(models.Model):
    STATUS = [('Draft','Draft'),('Published','Published')]
    question = models.ForeignKey(Question,on_delete = models.CASCADE)
    answer_txt = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=12,choices=STATUS,default='Draft')
    username = models.ForeignKey(User,on_delete = models.SET_NULL,null=True)
    upvotes = models.ManyToManyField(User , related_name = 'Upvotes' , blank=True)
    similarity = models.FloatField(null=True)

    def __str__(self):
        return f'{self.question.title} by {self.username.first_name}'

    def upvotesCount(self):
        return self.upvotes.count()

assignment/forms.py
from django import forms
from django.forms import ModelChoiceField
from .models import Student,Faculty,Branch,StudyYear,Course,Assignment,Question,Answer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from bootstrap_modal_forms.forms import BSModalForm




class ExtendedUserCreationForm(UserCreationForm):
    email = forms.EmailField(required = True)
    first_name = forms.CharField(max_length= 50)
    last_name = forms.CharField(max_length = 50)
    class Meta :
        model = User
        fields = ('username','email','first_name','last_name','password1','password2')

    def save(self , commit = True):
        user = super().save(commit = False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user

class StudentSignUpForm(forms.ModelForm):
    branch = ModelChoiceField(queryset=Branch.objects.all())
    year = ModelChoiceField(queryset=StudyYear.objects.all())
    class Meta :
        model = Student
        fields = ('rollnumber','branch','year')

class FacultySignUpForm(forms.ModelForm):
    branch = ModelChoiceField(queryset=Branch.objects.all())
    class Meta :
        model = Faculty
        fields = ('code','branch')




class CreateAssignmentForm(forms.ModelForm):
    course = forms.ModelChoiceField(queryset=None,empty_label=None,label = 'Please select course')
    deadline_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    def __init__(self, *args, **kwargs):   # no user here
        user = kwargs.pop('user', None)
        faculty = Faculty.objects.get(user = user)
        super(CreateAssignmentForm, self).__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.filter(faculty=faculty)

    class Meta:
        model = Assignment
        fields = ('number', 'course', 'deadline_date')


class AddAssignmentQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        widgets = {
            'modelAnswer': forms.Textarea(
                attrs={'placeholder': 'Not mandatory. You can use generate button from questions list section.'}),
        }
        exclude = ['username','date','assignment']

class AddAssignmentAnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        exclude = ['username','assignment','question','upvotes','similarity']

assignment/templates/Faculty_Dashboard/addAssignmentQuestion.html
<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Add Question</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{field}}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Create</button>
  </div>

</form>

assignment/templates/Faculty_Dashboard/add_assignment.html
{% extends "./base.html" %}

{% block breadcrumb%}

<li class="breadcrumb-item active">Add  Assignment</li>
{%endblock%}


{% load widget_tweaks %}

{% block content %}
  <h2>Add Assignment</h2>
  <form method="post">
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}

    <div class="form-group">
      <input class="btn btn-primary" type="submit" value="Save">
    </div>
  </form>
{% endblock %}

assignment/templates/Faculty_Dashboard/add_course.html
{% extends "./base.html" %}

{% block breadcrumb%}
<li class="breadcrumb-item "><a href="{% url 'ViewCourse' %}">All Course</a></li>
<li class="breadcrumb-item active">Course </li>
{%endblock%}

  {% load widget_tweaks %}

  {% block content %}
    <h2>Add / Update Course</h2>
    <form method="post">
      {% csrf_token %}

      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field|add_class:'form-control' }}
          {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      {% endfor %}

      <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Save">
      </div>
    </form>
  {% endblock %}

assignment/templates/Faculty_Dashboard/add_question.html
{% extends './base.html' %}

{% block breadcrumb%}
<li class="breadcrumb-item "><a href="{% url 'ViewAssignment' %}">Assignments</a></li>
<li class="breadcrumb-item"><a href="{% url 'assignment_detail' pk %}">Question list</a></li>
<li class="breadcrumb-item active">Add Question</li>
{%endblock%}

{% load widget_tweaks %}

{% block content %}
  <h2>Add Question</h2>
  <form method="post">
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}

    <div class="form-group">
      <input class="btn btn-primary" type="submit" value="Save">
    </div>
  </form>
{% endblock %}

assignment/templates/Faculty_Dashboard/assignment_detail.html
{% extends "./base.html" %}

{% block breadcrumb%}
<li class="breadcrumb-item "><a href="{% url 'ViewAssignment' %}"> All Assignments</a></li>
<li class="breadcrumb-item "><a href="{% url 'course_detail' assignment.course_id %}">Course Specific Assignments</a></li>
<li class="breadcrumb-item active">Question list</li>
{%endblock%}

{% block content %}
  <h1>Course:{{assignment.course }}</h1>

  <p><strong>Assignment:</strong> {{ assignment.number }}</p>
  <p><strong>publish_date:</strong> {{ assignment.publish_date }}</p>
  <p><strong>deadline:</strong> {{assignment.deadline_date}}</p>
  <div style="margin-left:20px;margin-top:20px">
    <h4>Questions</h4>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Question Title</th>
          <th scope="col">Question Marks</th>
          <th scope="col">Edit Question</th>
          <th scope="col">Delete Question</th>
          <th scope="col">View Submitted Answers</th>
          <th scope="col">Model Answer</th>
        </tr>
      </thead>
      <tbody>
        {% for question in assignment.question_set.all %}
        <tr>
          <td>{{ question.title }}</td>
          <td>{{ question.marks }}</td>
          <td> <a href="{% url 'UpdateQuestion'  assignment.id question.id %}">Edit</a> </td>
          <td> <a onclick="return confirm('Are you sure?');" href="{% url 'DeleteQuestion'  assignment_pk=assignment.id pk=question.id %}">Delete</a></td>
          <td> <a href="{% url 'AllSubmittedAnswers' question.id %}">View all answers</a></td>
          <td><a href="{% url 'viewModelAnswer' question.id %}">Model Answer</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <!-- Button trigger modal -->
<a class=" btn btn-primary" href="{% url 'CreateQuestion' pk=assignment.id %}">Add Question</a>
  </div>






{% endblock %}
{% block script %}

{% endblock %}

assignment/templates/Faculty_Dashboard/assignment_list.html
{% extends "./base.html" %}
{% block breadcrumb%}
<li class="breadcrumb-item active">Assignments</li>
{%endblock%}
{% block content %}

{% if assignment_list %}
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Assignment No.</th>
        <th scope="col">Course</th>
        <th scope="col">publish date</th>
        <th scope="col">Deadline Date</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
        <th scope="col">Questions</th>
      </tr>
    </thead>
    <tbody>
      {% for assignment in assignment_list %}
      <tr>
        <td>{{ assignment.number }}</td>
        <td>{{ assignment.course }}</td>
        <td>{{ assignment.publish_date }}</td>
        <td>{{ assignment.deadline_date }}</td>
        <td> <a href="{% url 'UpdateAssignment' assignment.id %}">Update</a> </td>
        <td> <a onclick="return confirm('Are you sure?');" href="{% url 'DeleteAssignment' assignment.id %}">Delete</a></td>
        <td><a href="{% url 'assignment_detail' assignment.id %}">View Questions</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>There are no assignments added yet !</p>
  {% endif %}
{% endblock %}

assignment/templates/Faculty_Dashboard/course_detail.html
{% extends "./base.html" %}

{% block breadcrumb%}
<li class="breadcrumb-item "><a href="{% url 'ViewCourse' %}">All Course</a></li>
<li class="breadcrumb-item active">Course Specific Assignment</li>
{%endblock%}

{% block content %}
  <h1>Course:{{course.name }}</h1>
  <p><strong>Semester:</strong> {{ course.semester }}</p>
  <p><strong>Branch:</strong> {{ course.branch }}</p>
  <p><strong>Year:</strong> {{course.year}}</p>
  <div style="margin-left:20px;margin-top:20px">
    <h4>Assignments related to this course</h4>
    {% if course.assignment_set.all %}
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Assignment Number</th>
          <th scope="col">Publish Date</th>
          <th scope="col">Deadline</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
          <th scope="col">View</th>
        </tr>
      </thead>
      <tbody>

        {% for assignment in course.assignment_set.all %}
        <tr>
          <td>{{ assignment.number }}</td>
          <td>{{ assignment.publish_date }}</td>
          <td>{{ assignment.deadline_date }}</td>
          <td> <a href="{% url 'UpdateCourseAssignment' assignment.id %}">Update</a> </td>
          <td> <a onclick="return confirm('Are you sure?');" href="{% url 'DeleteCourseAssignment' assignment.id %}">Delete</a></td>
          <td><a href="{% url 'assignment_detail'  assignment.id %}">View Questions</a></td>


        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>There are no assignments added yet !</p>
    {% endif %}

  </div>


{% endblock %}

assignment/templates/Faculty_Dashboard/index.html
{% extends "./base.html" %}
{% block content %}

  <h1>Welcome Prof.{{user.first_name}} {{user.last_name}} !</h1>
{% endblock %}

assignment/templates/Faculty_Dashboard/modelAnswer.html
{% extends "./base.html" %}
{% block breadcrumb %}
<li class="breadcrumb-item "><a href="{% url 'ViewAssignment' %}"> All Assignments</a></li>
<li class="breadcrumb-item "><a href="{% url 'course_detail' question.assignment.course_id %}">Course Specific Assignments</a></li>
<li class="breadcrumb-item active"><a href="{% url 'assignment_detail' question.assignment.id %}">Questions list</a></li>
<li class="breadcrumb-item active">Model Answer</li>
{% endblock %}

{% block content %}
<textarea name="modelAnswer" rows="15" cols="80" disabled>
  {{modelAnswer}}
</textarea>
<br>
<a class="btn btn-primary" href="{% url 'generateModelAnswer' id %}">Generate Model Answer</a>

<div class="">
  <h5>If you experience error 500, please add the model answer manually. Sometimes this module do not work due to network communication error or
  probably because source website is not allowing web-scraping.</h5>
</div>

{% endblock %}

assignment/templates/Faculty_Dashboard/question_bank.html
{% extends "./base.html" %}
{% block breadcrumb%}
<li class="breadcrumb-item active">Add Question Bank</li>
{%endblock%}

{% block content %}
<div class="col-md-8" style="margin-bottom:5px">
<form method="get" action="{% url 'GetQuestions' %}">
  <div class="form-group">
    <label for="exampleFormControlInput1">Question Bank Title</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Ex. Question Bank for UT-1">
  </div>
  <div class="form-group">
    <label >Course</label>
    <select class="form-control" name="course" id="course">
      <option  value="Z">Select a course</option>
      {% for course in courses %}
      <option value="{{course.id}}">{{course}}</option>
      {% endfor %}
    </select>
  </div>

  <div class="form-group">
    <label for="assignment">Select Assigment(s)</label>
    <select multiple size="5" class="form-control" id="assignment" name="assignment" disabled="true" placeholder="hold ctrl to select multiple assignment">
      <option disabled>hold ctrl to (de)select multiple assignment</option>
    </select>
  </div>

  <div class="form-group">
    <label for="exampleFormControlInput1">Enter maximum number of questions</label>
    <input required name="maxQuestions" type="integer" class="form-control" id="exampleFormControlInput1" placeholder="Ex. 10">
  </div>


  <button type="submit" class="submit-btn btn btn-primary">Generate</button>
<button class="submit-btn btn btn-primary" id="PrintQB">Print</button>

</form>

</div>

{% if question_list %}
<form class="" action="" method="post">

<table class="table" id="QB">
  <thead class="thead-light">
    <td scope="col">Question</td>
    <td scope="col">Assigment</td>
  </thead>
  {% for question in question_list %}
  <tr>
    <td>{{question.title}}</td>
    <td>{{question.assignment}}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
function printData()
{
   var divToPrint=document.getElementById("QB");
   newWin= window.open("");
   newWin.document.write(divToPrint.outerHTML);
   newWin.print();
   newWin.close();
}

$('button#PrintQB').on('click',function(){
printData();
})

$(document).ready(
function() {
$("select#course").change(function() {
if ($(this).val() == 'Z') {
$("select#assignment").html("<option>Select Assignment(s)</option>");
$("select#assignment").attr('disabled', true);
}
else {
// var url = "selectedCourse/" + $(this).val() + "/all_json_assignments";
var id = parseInt($(this).val());
var url = '{% url "SendCourse" id=999 %}'.replace('999',id);
var brand = $(this).val();
$.getJSON(url, function(assignments) {
  var options = '<option disabled value="Z">Select Assignment(s)-Hold CTRL and select multiple assignment</option>';
    for (var i = 0; i < assignments.length; i++) {
    options += '<option value="' + assignments[i].pk + '">' + assignments[i].fields['number'] + '</option>';
    }
  $("select#assignment").html(options);
  $("select#assignment option:first").attr('selected', 'selected');
  $("select#assignment").attr('disabled', false);
});
}
});


$("select#assignment").change(function(vent) {
if ($(this).val() == -1) {
return;
}

});
});






</script>
{% endblock %}

assignment/templates/Faculty_Dashboard/submitted_answers.html
{% extends "./base.html" %}

{% block breadcrumb%}
<li class="breadcrumb-item "><a href="{% url 'ViewAssignment' %}"> All Assignments</a></li>
<li class="breadcrumb-item "><a href="{% url 'course_detail' question.assignment.course_id %}">Course Specific</a></li>
<li class="breadcrumb-item "><a href="{% url 'assignment_detail' question.assignment.id %}">Question list</a></li>
<li class="breadcrumb-item active">All Submitted Answers</li>
{%endblock%}

{% block content %}
<h1> QUESTION: {{question }}</h1>


  <div style="margin-left:20px;margin-top:20px">
    <h4>Questions</h4>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Roll Number</th>
          <th scope="col">Name</th>
          <th scope="col">Date</th>
          <th scope="col">Answer</th>
          <th scope="col">Similarity</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for answer in answers %}
        <tr>
          <td>{{ answer.username.student.rollnumber}}</td>
          <td>{{ answer.username.first_name}} {{ answer.username.last_name}}</td>
          <td>{{ answer.date}}</td>
          <td>{{answer.answer_txt}}</td>
          <td>{{answer.similarity}}</td>
          <td><a class="btn btn-warning" href="{% url 'RejectAnswer' qid=question.id  ansID=answer.id  %}">Reject</a></td>

        </tr>
      {% endfor %}
      </tbody>
    </table>

  </div>






{% endblock %}
{% block script %}

{% endblock %}

assignment/templates/Faculty_Dashboard/update_assignment.html
{% extends "./base.html" %}

{% block breadcrumb%}
<li class="breadcrumb-item "><a href="{% url 'ViewAssignment' %}"> All Assignments</a></li>
<li class="breadcrumb-item "><a href="{% url 'ViewCourse' %}">All Course</a></li>
<li class="breadcrumb-item "><a href="{% url 'course_detail' assignment.course_id %}">Course Specific Assignments</a></li>
<li class="breadcrumb-item active">Update Assignment</li>
{%endblock%}


{% load widget_tweaks %}

{% block content %}
  <h2>Update Assignment</h2>
  <form method="post">
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}

    <div class="form-group">
      <input class="btn btn-primary" type="submit" value="Save">
    </div>
  </form>
{% endblock %}